# Generated by Django 1.10.5 on 2017-01-31 13:50


from django.db import migrations, models
import django.utils.timezone

import jsonfield.fields
import model_utils.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FailedTask',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('task_name', models.CharField(max_length=255)),
                ('task_id', models.CharField(db_index=True, max_length=255)),
                ('args', jsonfield.fields.JSONField(blank=True)),
                ('kwargs', jsonfield.fields.JSONField(blank=True)),
                ('exc', models.CharField(max_length=255)),
                ('datetime_resolved', models.DateTimeField(blank=True, db_index=True, default=None, null=True)),
            ],
        ),
        migrations.AlterIndexTogether(
            name='failedtask',
            index_together={('task_name', 'exc')},
        ),
    ]
